version: "3"

networks: 
  elk_net:
    driver: bridge

volumes:
  es_volume:
    driver: local


services:

  logstash:
    build:
      context: ./logstash
    restart: always
    volumes:
      - ./logs/input:/logs/input
      - ./logs/output:/logs/output
    ports:
        - "5000:5000"
    networks: 
        - elk_net
    depends_on:
      - elasticsearch

  
  # 录入消息只用在 ./logs/input/ 目录下输入数据就能进程测试
  # 启动后可以在本地 http://localhost:9200/_search?pretty  查看收到的消息
  elasticsearch:
    build:
      context: ./elasticsearch
    restart: always
    # deploy:
    #   # 默认开启三个容器, 每个容器上限 1核1G, 下限 0.25核20M
    #   mode: replicated
    #   replicas: 3
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G
    #     reservations:
    #       cpus: '0.25'
    #       memory: 20M
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - es_volume:/usr/share/elasticsearch/data
    networks:
      - elk_net
  
  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk_net
    depends_on:
      - elasticsearch
    

    